const ActionTypes = {
    TEMPERATURE_CHANGE: 'TEMPERATURE_CHANGE',
    DISPLAY_CHANGE: 'DISPLAY_CHANGE',
    CHART_UPDATE: 'CHART_UPDATE',
    CHART_INIT: 'CHART_INIT',
    WAMP_CONNECTION_INITIATED: 'WAMP_CONNECTION_INITIATED',
    WAMP_CONNECTION_SUCCESS: 'WAMP_CONNECTION_SUCCESS',
    WAMP_ERROR: 'WAMP_ERROR',
    WAMP_SUBSCRIPTION_SUCCESS: "WAMP_SUBSCRIPTION_SUCCESS"
};

export default ActionTypes;
